blueprint:
  name: Hue Dimmer v2 z2m MQTT
  description: Version 1 - Triggers on MQTT events, does dimming on hold button.
  domain: automation
  author: Chris Waldmeyer
  source_url: https://raw.githubusercontent.com/Basop/homeassistant/refs/heads/main/Blueprints/Hue_dimmer_v2_z2m_mqtt.yaml
  input:
    mqtt_topic:
      name: eg. zigbee2mqtt/dimmer_main/action
      description: The dimmer topic assigned to the area
      default: "zigbee2mqtt/dimmer_study_main/action"
      selector:
        text:
    lights:
      name: Lights
      description: The lights assigned to this dimmer
      default: ""
      selector:
        entity:
          multiple: true
          filter:
            - domain:
                - light
    default_brightness:
      name: Default Brightness
      description: set the default brightness when turning on the light
      default: "90"
      selector:
        number:
          min: 5.0
          max: 95.0
          unit_of_measurement: percent
          mode: slider
          step: 1.0
    scene_helper:
      name: Scene Helper
      description: Select the scene helper assigned to this area.
      default: ""
      selector:
        entity:

description: ""
triggers:
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: up_hold
    id: up-hold
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: up_hold_release
    id: up-press-release
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: down_hold
    id: down-hold
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: down_hold_release
    id: down-hold-release
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: on_press
    id: on-press
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: off_press
    id: off-press
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - up-hold
        sequence:
          - repeat:
              sequence:
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_step_pct: 5
                    transition: 0.6
                  target:
                    entity_id: !input lights
              until:
                - condition: trigger
                  id:
                    - up-hold
      - conditions:
          - condition: trigger
            id:
              - down-hold
        sequence:
          - repeat:
              sequence:
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 200
                - action: light.turn_on
                  metadata: {}
                  data:
                    brightness_step_pct: -5
                    transition: 0.6
                  target:
                    entity_id: !input lights
              until:
                - condition: trigger
                  id:
                    - down-hold
      - conditions:
          - condition: trigger
            id:
              - on-press
        sequence:
          - action: light.toggle
            metadata: {}
            data:
              brightness_pct: 90
              transition: 1
            target:
              entity_id: !input lights
      - conditions:
          - condition: trigger
            id:
              - off-press
        sequence:
          - action: select.select_next
            metadata: {}
            data:
              cycle: true
            target:
              entity_id: !input scene_helper
mode: single